INVALID_APPS = {312710: {'name': 'Broadsword : Age of Chivalry',
                         'header_image': 'https://cdn.cloudflare.steamstatic.com/steam/apps/312710/header.jpg'},
                335080: {'name': 'Biology Battle',
                         'header_image': 'https://cdn.cloudflare.steamstatic.com/steam/apps/335080/header.jpg'},
                428430: {'name': 'Endorlight',
                         'header_image': 'https://cdn.cloudflare.steamstatic.com/steam/apps/428430/header.jpg'},
                488680: {'name': 'Tower Defense Ultimate',
                         'header_image': 'https://cdn.cloudflare.steamstatic.com/steam/apps/488680/header.jpg'},
                492660: {'name': 'Featherpunk Prime',
                         'header_image': "https://cdn.cloudflare.steamstatic.com/steam/apps/492660/header.jpg"},
                526790: {'name': 'Monsti',
                         'header_image': "https://cdn.cloudflare.steamstatic.com/steam/apps/526790/header.jpg"},
                545230: {'name': 'Professor Nasty Time: The Stupidly Unfair Test Simulator 2016',
                         'header_image': "https://cdn.cloudflare.steamstatic.com/steam/apps/545230/header.jpg"},
                548930: {'name': 'Mankind Defender',
                         'header_image': "https://cdn.cloudflare.steamstatic.com/steam/apps/548930/header.jpg"},
                562650: {'name': 'Cube Master',
                         'header_image': "https://cdn.cloudflare.steamstatic.com/steam/apps/562650/header.jpg"},
                570550: {'name': 'Fearful Symmetry',
                         'header_image': "https://cdn.cloudflare.steamstatic.com/steam/apps/570550/header.jpg"},
                489890: {'name': 'Puzzles At Mystery Manor',
                         'header_image': "https://cdn.cloudflare.steamstatic.com/steam/apps/489890/header.jpg"},
                648590: {'name': '428 〜封鎖された渋谷で〜',
                         'header_image': 'https://cdn.cloudflare.steamstatic.com/steam/apps/648590/header.jpg'},
                737230: {'name': 'Rising Storm 2: Vietnam CTB Beta',
                         'header_image': 'https://cdn.cloudflare.steamstatic.com/steamcommunity/public/images/apps/737230/ea3b9893081446dfe0139bae2cc942851593a40c.jpg'},
                368420: {'name': 'Mirage: Arcane Warfare',
                         'header_image': 'https://cdn.cloudflare.steamstatic.com/steam/apps/368420/header.jpg'},
                710750: {'name': 'Think of the Children Beta',
                         'header_image': 'https://cdn.cloudflare.steamstatic.com/steam/apps/710750/header.jpg'},
                397080: {'name': 'Magicka 2: Spell Balance Beta',
                         'header_image': "https://steamdb.info/static/img/applogo.svg"},
                324060: {'name': 'Planet Ancyra Chronicles',
                         'header': 'https://cdn.cloudflare.steamstatic.com/steam/apps/324060/header.jpg'},
                774941: {'name': 'Squad - Public Testing',
                         'header_image': 'https://cdn.cloudflare.steamstatic.com/steam/apps/774941/header.jpg'},
                44630: {'name': 'RACE 07 - Formula RaceRoom Add-On',
                        'header_image': 'https://cdn.cloudflare.steamstatic.com/steamcommunity/public/images/apps/44630/2b03526ffc33573d715a0e7a2f2b339c9fc25a25.jpg'},
                226980: {'name': 'Pinball FX2',
                         'header_image': 'https://cdn.cloudflare.steamstatic.com/steam/apps/226980/header.jpg'}}
