INVALID_APPS = {312710: {'name': 'Broadsword : Age of Chivalry',
                         'header_image': 'https://cdn.cloudflare.steamstatic.com/steam/apps/312710/header.jpg',
                         'developers': ['Hoplite Research LLC'], 'publishers': ['KISS ltd'],
                         'price_overview': {'currency': 'N/A'}},
                335080: {'name': 'Biology Battle',
                         'header_image': 'https://cdn.cloudflare.steamstatic.com/steam/apps/335080/header.jpg',
                         'developers': ['Novaleaf Game Studios'], 'publishers': ['Meridian4'],
                         'price_overview': {'currency': 'N/A'}},
                428430: {'name': 'Endorlight',
                         'header_image': 'https://cdn.cloudflare.steamstatic.com/steam/apps/428430/header.jpg',
                         'developers': ['Unika GamesUnika Games'], 'publishers': ['Unika Games'],
                         'price_overview': {'currency': 'N/A'}},
                488680: {'name': 'Tower Defense Ultimate',
                         'header_image': 'https://cdn.cloudflare.steamstatic.com/steam/apps/488680/header.jpg',
                         'developers': ['Dev4play'], 'publishers': ['Dev4play'], 'price_overview': {'currency': 'N/A'}},
                492660: {'name': 'Featherpunk Prime',
                         'header_image': 'https://cdn.cloudflare.steamstatic.com/steam/apps/492660/header.jpg',
                         'developers': ['Super Hatch Games'], 'publishers': ['Super Hatch Games'],
                         'price_overview': {'currency': 'N/A'}},
                526790: {'name': 'Monsti',
                         'header_image': 'https://cdn.cloudflare.steamstatic.com/steam/apps/526790/header.jpg',
                         'developers': ['Unika GamesUnika Games'], 'publishers': ['Unika GamesUnika Games'],
                         'price_overview': {'currency': 'N/A'}},
                545230: {'name': 'Professor Nasty Time: The Stupidly Unfair Test Simulator 2016',
                         'header_image': 'https://cdn.cloudflare.steamstatic.com/steam/apps/545230/header.jpg',
                         'developers': ['Barkalar Games'], 'publishers': ['Barkalar Games'],
                         'price_overview': {'currency': 'N/A'}},
                548930: {'name': 'Mankind Defender',
                         'header_image': 'https://cdn.cloudflare.steamstatic.com/steam/apps/548930/header.jpg',
                         'developers': ['Dev4play'], 'publishers': ['Dev4play'], 'price_overview': {'currency': 'N/A'}},
                562650: {'name': 'Cube Master',
                         'header_image': 'https://cdn.cloudflare.steamstatic.com/steam/apps/562650/header.jpg',
                         'developers': ['Zebatuq'], 'publishers': ['Obidak Software'],
                         'price_overview': {'currency': 'N/A'}},
                570550: {'name': 'Fearful Symmetry',
                         'header_image': 'https://cdn.cloudflare.steamstatic.com/steam/apps/570550/header.jpg',
                         'developers': None, 'publishers': None, 'price_overview': {'currency': 'N/A'}},
                489890: {'name': 'Puzzles At Mystery Manor',
                         'header_image': 'https://cdn.cloudflare.steamstatic.com/steam/apps/489890/header.jpg',
                         'developers': ['EnsenaSoft'], 'publishers': ['EnsenaSoft'],
                         'price_overview': {'currency': 'N/A'}},
                648590: {'name': '428 〜封鎖された渋谷で〜',
                         'header_image': 'https://cdn.cloudflare.steamstatic.com/steam/apps/648590/header.jpg',
                         'developers': ['Spike Chunsoft Co., Ltd.', 'Abstraction Games'],
                         'publishers': ['Spike Chunsoft Co., Ltd.'],
                         'price_overview': {'currency': 'JPY', 'initial': 396000}},
                737230: {'name': 'Rising Storm 2: Vietnam CTB Beta',
                         'header_image': 'https://cdn.cloudflare.steamstatic.com/steamcommunity/public/images/apps/737230/ea3b9893081446dfe0139bae2cc942851593a40c.jpg',
                         'developers': None, 'publishers': None, 'price_overview': {'currency': 'N/A'}},
                368420: {'name': 'Mirage: Arcane Warfare',
                         'header_image': 'https://cdn.cloudflare.steamstatic.com/steam/apps/368420/header.jpg',
                         'developers': ['Torn Banner Studios'], 'publishers': ['Torn Banner Studios'],
                         'price_overview': {'currency': 'N/A'}},
                710750: {'name': 'Think of the Children Beta',
                         'header_image': 'https://cdn.cloudflare.steamstatic.com/steam/apps/710750/header.jpg',
                         'developers': None, 'publishers': None, 'price_overview': {'currency': 'N/A'}},
                397080: {'name': 'Magicka 2: Spell Balance Beta', 'header_image': None, 'developers': None,
                         'publishers': None, 'price_overview': {'currency': 'N/A'}},
                324060: {'name': 'Planet Ancyra Chronicles',
                         'header_image': 'https://cdn.cloudflare.steamstatic.com/steam/apps/324060/header.jpg',
                         'developers': ['Pulsetense Games'], 'publishers': ['KISS ltd'],
                         'price_overview': {'currency': 'N/A'}},
                774941: {'name': 'Squad - Public Testing',
                         'header_image': 'https://cdn.cloudflare.steamstatic.com/steam/apps/774941/header.jpg',
                         'developers': ['Offworld Industries'], 'publishers': ['Offworld Industries'],
                         'price_overview': {'currency': 'N/A'}},
                44630: {'name': 'RACE 07 - Formula RaceRoom Add-On',
                        'header_image': 'https://cdn.cloudflare.steamstatic.com/steamcommunity/public/images/apps/44630/2b03526ffc33573d715a0e7a2f2b339c9fc25a25.jpg',
                        'developers': None, 'publishers': None, 'price_overview': {'currency': 'N/A'}},
                226980: {'name': 'Pinball FX2',
                         'header_image': 'https://cdn.cloudflare.steamstatic.com/steam/apps/226980/header.jpg',
                         'developers': ['Zen Studios'], 'publishers': ['Microsoft Studios'],
                         'price_overview': {'currency': 'N/A'}},
                336790: {'name': 'KWAAN',
                         'header_image': 'https://cdn.cloudflare.steamstatic.com/steam/apps/336790/header.jpg',
                         'developers': ['Ankama Canada'], 'publishers': ['Ankama Games'],
                         'price_overview': {'currency': 'N/A'}},
                737010: {'name': 'Warhammer: Vermintide 2 Closed Test', 'header_image': None, 'developers': None,
                         'publishers': None, 'price_overview': {'currency': 'N/A'}},
                12240: {'name': 'Grand Theft Auto: Vice City',
                        'header_image': 'https://cdn.cloudflare.steamstatic.com/steam/apps/12240/header.jpg',
                        'developers': ['TransGaming Inc.'], 'publishers': None, 'price_overview': {'currency': 'N/A'}},
                12230: {'name': 'Grand Theft Auto III',
                        'header_image': 'https://cdn.cloudflare.steamstatic.com/steam/apps/12230/header.jpg',
                        'developers': ['TransGaming Inc.'], 'publishers': None, 'price_overview': {'currency': 'N/A'}},
                # あるかも
                33540: {'name': 'Dawn of Magic 2',
                        'header_image': 'https://steamcdn-a.akamaihd.net/steam/apps/33540/header.jpg?t=1602079757',
                        'developers': ['SkyFallen Entertainment'], 'publishers': ['1C Entertainment'],
                        'price_overview': {'currency': 'JPY', 'initial': 29800}},
                711030: {'name': 'Hover - Workshop Tool',
                         'header_image': 'https://cdn.cloudflare.steamstatic.com/steamcommunity/public/images/apps/711030/92351b32035dad947dc9037b6af67871ca6a5946.jpg',
                         'developers': None, 'publishers': None, 'price_overview': {'currency': 'N/A'}},
                931180: {'name': 'Conan Exiles - Testlive Client',
                         'header_image': 'https://cdn.cloudflare.steamstatic.com/steam/apps/931180/header.jpg',
                         'developers': ['Funcom'], 'publishers': ['Funcom'], 'price_overview': {'currency': 'N/A'}},
                214320: {'name': 'Dollar Dash',
                         'header_image': 'https://cdn.cloudflare.steamstatic.com/steam/apps/214320/header.jpg',
                         'developers': ['Candygun Games'], 'publishers': ['Kalypso Media Digital'],
                         'price_overview': {'currency': 'N/A'}},
                240160: {'name': 'Duke Nukem',
                         'header_image': 'https://cdn.cloudflare.steamstatic.com/steam/apps/240160/header.jpg',
                         'developers': ['3D Realms'], 'publishers': ['3D Realms (Apogee Software)'],
                         'price_overview': {'currency': 'N/A'}},
                208610: {'name': 'Skullgirls ∞Endless Beta∞',
                         'header_image': 'https://cdn.cloudflare.steamstatic.com/steamcommunity/public/images/apps/208610/33974b81779c888b3b4d9c4b91d86ef0907b11f3.jpg',
                         'developers': None, 'publishers': None, 'price_overview': {'currency': 'N/A'}},
                224060: {'name': 'Deadpool',
                         'header_image': 'https://cdn.cloudflare.steamstatic.com/steam/apps/224060/header.jpg',
                         'developers': ['High Moon Studios'], 'publishers': ['Activision'],
                         'price_overview': {'currency': 'N/A'}},
                201700: {'name': 'DiRT Showdown',
                         'header_image': 'https://cdn.cloudflare.steamstatic.com/steam/apps/201700/header.jpg',
                         'developers': ['Codemasters Racing Studio'], 'publishers': ['Codemasters'],
                         'price_overview': {'currency': 'N/A'}},
                43110: {'name': 'Metro 2033',
                        'header_image': 'https://cdn.cloudflare.steamstatic.com/steam/apps/43110/header.jpg',
                        'developers': ['4A Games'], 'publishers': ['Deep Silver'],
                        'price_overview': {'currency': 'N/A'}},
                232150: {'name': 'Killing Floor 2 - SDK',
                         'header_image': 'https://cdn.cloudflare.steamstatic.com/steamcommunity/public/images/apps/232150/b341754b0ca9192271226eb60c4e2a70b5b66ebe.jpg',
                         'developers': None, 'publishers': None, 'price_overview': {'currency': 'N/A'}}}
