# Generated by Django 3.1.4 on 2020-12-13 04:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('steam', '0003_achievement'),
    ]

    operations = [
        migrations.AddField(
            model_name='achievement',
            name='icon',
            field=models.URLField(default=''),
            preserve_default=False,
        ),
    ]
