# Generated by Django 3.1.4 on 2020-12-13 05:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('steam', '0004_achievement_icon'),
    ]

    operations = [
        migrations.AddField(
            model_name='achievement',
            name='hidden',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
    ]
