# Generated by Django 3.1.4 on 2020-12-15 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('steam', '0006_ownedgames'),
    ]

    operations = [
        migrations.CreateModel(
            name='GameList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.JSONField()),
            ],
        ),
    ]
